기초/n 번째 원소까지
MinQyu/algorithm pull request #12
Opened 2023-12-26 14:12 UTC by MinQyu

https://school.programmers.co.kr/learn/courses/30/lessons/181889

2023-12-27 04:46 UTC, hyeonQyu commented on programmersJS/n 번째 원소까지.js
> +        answer.push(num_list[i]);
Array의 slice() 메소드를 사용해서 코드를 바꿔보도록

2023-12-27 04:46 UTC, hyeonQyu requested changes
Array.slice() 메소드를 사용해서 코드를 바꿔보도록

2023-12-28 10:42 UTC, MinQyu reviewed
slice 메소드 이용, 코드 수정

2024-01-06 08:24 UTC, hyeonQyu approved these changes

2024-01-07 02:20 UTC, merged