기초/배열의 원소 삭제하기
MinQyu/algorithm pull request #24
Opened 2024-01-03 08:40 UTC by MinQyu

https://school.programmers.co.kr/learn/courses/30/lessons/181844

2024-01-06 09:01 UTC, hyeonQyu requested changes

2024-01-06 09:01 UTC, hyeonQyu commented on programmersJS/배열의 원소 삭제하기.js
> +            answer.splice(answer.indexOf(delete_list[i]), 1);
이 코드는 indexOf 때문에 2중 for문이야. 그럼 시간복잡도가 n^2인거 알고리즘 시간에서 배웠지?
나는 이 문제를 n의 시간 복잡도로 해결 할 수 있을 것 같아.
힌트를 주자면 Map 자료구조를 한번 사용해봐.
잘 모르겠으면 물어봐도 좋아.

2024-01-14 11:28 UTC, MinQyu reviewed
처음에 map 자료구조가 아니고 map()을 써서 하려다가 실패함. 
const answer = arr.map(e => delete_list.includes(e) ? e.pop : e);
null을 포함하는 배열이 리턴됨. 여러가지 시도해보다가 map()으로는 특정 요소 삭제가 불가능한 것을 알게됨. 이후 filter() 이용해 간단하게 구현함,

2024-01-30 07:22 UTC, hyeonQyu commented
내 말의 요지는 2중 for문을 사용하지 말아보잔 뜻이야.
코드가 간결해졌다고 더 좋아진게 아니라 성능적으로 충분히 더 개선할 수 있어보임
내가 말한건 map 자료구조야

2024-01-30 11:00 UTC, MinQyu reviewed
set 자료구조를 이용해 수정

2024-02-02 07:41 UTC, hyeonQyu approved these changes
아주 굿

2024-02-02 09:54 UTC, merged