기초/부분 문자열 이어 붙여 묹자열 만들기
MinQyu/algorithm pull request #29
Opened 2024-01-05 07:37 UTC by MinQyu

https://school.programmers.co.kr/learn/courses/30/lessons/181911

2024-01-06 09:13 UTC, hyeonQyu requested changes
이것도 마찬가지로 Array 내장 함수를 사용해서 해보자
지금까지 문제 중에서 let이 필요한 경우는 한번도 없었어.

2024-01-14 12:16 UTC, MinQyu reviewed
const로 선언 후, push와 join 이용해서 수정

2024-01-30 07:27 UTC, hyeonQyu commented
다시 수정하시오

2024-01-30 08:26 UTC, MinQyu reviewed
reduce 이용해 수정

2024-02-02 07:42 UTC, hyeonQyu approved these changes
담부터는 읽기 좋게 짜는 것도 함께 고려해보자

2024-02-02 09:55 UTC, merged