기초/할 일 목록
MinQyu/algorithm pull request #30
Opened 2024-01-05 07:44 UTC by MinQyu

https://school.programmers.co.kr/learn/courses/30/lessons/181885

2024-01-06 09:11 UTC, hyeonQyu requested changes
이전 PR을 복기하면서 Array의 내장 함수로 다시 해결해보도록

2024-01-18 06:57 UTC, MinQyu reviewed
filter를 이용해 해결

2024-01-30 07:29 UTC, hyeonQyu commented
finished[i] ? null : arr 이 문장은 필요 없음
filter 문서를 다시 읽어보면 알 수 있겠지만 filter 콜백 함수는 boolean값을 리턴하면 됨
더 간단하게 수정해봐

2024-01-30 08:31 UTC, MinQyu reviewed
boolean 값만 사용하도록 수정

2024-02-02 07:42 UTC, hyeonQyu approved these changes
굿

2024-02-02 09:56 UTC, merged