입문/합성수 찾기
MinQyu/algorithm pull request #51
Opened 2024-01-23 08:21 UTC by MinQyu

https://school.programmers.co.kr/learn/courses/30/lessons/120846

2024-02-06 06:08 UTC, hyeonQyu commented on 합성수 찾기.js.txt
> +        tmp.length>=3 ? answer+=1 : answer+=0;
이런건 if(tmp.length >= 3) answer++;
이렇게 처리할 수도 있겠지?

2024-02-06 06:11 UTC, hyeonQyu requested changes
이거는 꽤 복잡함.
함수 써서 리팩토링하면 충분히 읽기 좋게 만들 수 있을듯

2024-02-06 12:16 UTC, MinQyu reviewed
약수의 개수를 구하는 함수를 따로 정의함.

2024-04-04 01:07 UTC, hyeonQyu commented on 합성수 찾기.js
> +        if (countNumOfSub(i) >= 3) answer++;
3이 무엇을 의미하는지, 4가 무엇을 의미하는지 알 수 없음
코드를 보고 무슨 의도인지 알 수 있게 상수로 만들어서 사용하는것이 바람직함

2024-04-04 01:07 UTC, hyeonQyu approved these changes

2024-04-04 03:41 UTC, merged