입문/팩토리얼
MinQyu/algorithm pull request #55
Opened 2024-01-24 11:10 UTC by MinQyu

https://school.programmers.co.kr/learn/courses/30/lessons/120848

2024-04-04 01:10 UTC, hyeonQyu approved these changes

2024-04-04 01:10 UTC, hyeonQyu requested changes
배열 내장 함수를 사용해서 더 보기 좋게 작성할 수 있을듯

2024-04-07 09:20 UTC, MinQyu commented
1~10으로 초기화한 배열을 사용해서 다시 작성

2024-04-12 03:04 UTC, hyeonQyu commented
**배열 내장 함수**를 사용해서 다시

2024-04-14 08:40 UTC, MinQyu commented
reduce를 사용해서 고쳤으나, 처음 했던 코드가 가장 좋아보임.

2024-04-16 02:49 UTC, hyeonQyu commented
미안.. 이건 내가 문제 정확히 안보고 한거같다..
너가 처음에 한 방식이 맞는거같아

2024-04-16 02:49 UTC, hyeonQyu approved these changes

2024-04-16 06:21 UTC, merged