입문/k의 개수
MinQyu/algorithm pull request #56
Opened 2024-01-24 11:23 UTC by MinQyu

https://school.programmers.co.kr/learn/courses/30/lessons/120887

2024-04-04 01:12 UTC, hyeonQyu requested changes
이것도 틀린 것은 아니지만 배열 내장함수 사용하는 것으로 바꿔보자

2024-04-05 13:21 UTC, MinQyu commented
Array.from을 사용해서 다시 풀어봄

2024-04-12 03:05 UTC, hyeonQyu commented
join하고 바로 split? 합쳤다 나누는걸 굳이 왜하는거지?

2024-04-14 08:53 UTC, MinQyu commented
예를들어 i가 8 j가 12면 [8, 9, 10, 11, 12] 배열을 이런식으로 만들었다가 89101112 -> ['8', '9' , '1' , '0' , '1', '1', '1', '2'] 이렇게 쪼갠거야

2024-04-16 02:51 UTC, hyeonQyu approved these changes

2024-04-16 06:25 UTC, merged