입문/가까운 수
MinQyu/algorithm pull request #58
Opened 2024-01-24 12:12 UTC by MinQyu

https://school.programmers.co.kr/learn/courses/30/lessons/120890

처음에 '가장 가까운 수가 여러 개일 경우 더 작은 수를 return 합니다.' 라는 제약사항을 고려 안하고 or 연산 없이 코드를 짰다가 고침.

2024-04-04 01:18 UTC, hyeonQyu requested changes

2024-04-04 01:18 UTC, hyeonQyu commented on programmersJS/가까운 수.js
> +}
코드가 안읽힘
읽기 쉽게 고쳐봐

2024-04-05 14:59 UTC, MinQyu commented
함수를 사용해 가독성 개선

2024-04-12 03:06 UTC, hyeonQyu commented
개선할 수 있는 부분이 더 있음

2024-04-14 09:04 UTC, MinQyu commented
거리를 상수값으로 선언하고, 삼항연산자를 if문으로 품

2024-04-16 02:52 UTC, hyeonQyu approved these changes

2024-04-16 06:28 UTC, merged