입문/옹알이
MinQyu/algorithm pull request #60
Opened 2024-01-24 12:55 UTC by MinQyu

https://school.programmers.co.kr/learn/courses/30/lessons/120956

입문 문제중 정답률이 가장 낮은 문제인데, 정답률 높은순으로 풀다가 궁금해서 풀어봄. replace로 치환하는 방식으로 풀었는데, 정규식으로 필터링하면 더 간단할거같음. 정규식 표현법 공부하고 다시 풀어볼 예정

2024-04-04 01:24 UTC, hyeonQyu requested changes

2024-04-04 01:24 UTC, hyeonQyu commented on programmersJS/옹알이.js
> +}
애초에 첨부터 bablling.filter로 할 수 있을텐데

2024-04-04 01:25 UTC, hyeonQyu commented on programmersJS/옹알이.js
> +}
replace라는것도 필요 없음

2024-04-14 10:45 UTC, MinQyu commented
정규표현식으로 다시품.
/^(aya|ye|woo|ma)+$/
^$ : 문자열의 시작과 끝을 나타내는 어서션
() : 캡처링 그룹
+ : 캡처링 그룹에 해당하는 문자가 반복됨을 나타내는 수량자

2024-04-16 02:58 UTC, hyeonQyu approved these changes
정규식으로 푼 접근은 이전 방식보다 좋음
다만 내가 너한테 얘기하고자 했던것은
```javascript
function solution(babbling) {
    const bab = ["aya", "ye", "woo", "ma"];
    for (i = 0; i < babbling.length; i++) {
        for (j = 0; j < 4; j++) {
            babbling[i].includes(bab[j]) ? babbling[i] = babbling[i].replace(bab[j], 1) : null;
        }
    }
    return babbling.filter(e => Number(e)).length;
}
```
이 코드를
```javascript
function solution(babbling) {
    const bab = ["aya", "ye", "woo", "ma"];

    const isAble = (str) => {
        // 너가  for (j = 0; j < 4; j++) {
        //    babbling[i].includes(bab[j]) ? babbling[i] = babbling[i].replace(bab[j], 1) : null;
        //} 로 돌렸던 로직의 결과를 반환
    }

    return babbling.filter(isAble).length;
}
```
이렇게 바꿀 수 있다는걸 말하고 싶었음

2024-04-16 06:33 UTC, merged