입문/한 번만 등장한 문자
MinQyu/algorithm pull request #61
Opened 2024-01-24 13:07 UTC by MinQyu

https://school.programmers.co.kr/learn/courses/30/lessons/120896

2024-04-04 01:28 UTC, hyeonQyu requested changes

2024-04-04 01:28 UTC, hyeonQyu commented on programmersJS/한 번만 등장한 문자.js
> +    return s.split('').sort().filter((e, i, arr) => arr.filter(k => k == e).length === 1).join('');
sort 부분을 제외하고
filter가 두번 들어가니 시간복잡도가 n^2가 되는데
n으로 충분히 만들 수 있을 것 같음

2024-04-07 06:40 UTC, MinQyu commented
reduce를 이용해 앞 뒤 요소를 검사하도록 변경

2024-04-12 03:14 UTC, hyeonQyu approved these changes
이것도 정답이긴 하지만 map을 썼으면 좀 더 알아보기 쉽게 짤 수 있었을듯

2024-04-14 09:06 UTC, merged