입문/외계어 사전
MinQyu/algorithm pull request #71
Opened 2024-01-28 10:49 UTC by MinQyu

https://school.programmers.co.kr/learn/courses/30/lessons/120869

2024-04-12 03:36 UTC, hyeonQyu requested changes
spell은 변하지 않는 값이기 때문에 매번 for문 순회할때마다 sort().join()할 필요 없음
그리고 sort().join()이라는 과정이 순서를 맞춰서 문자열로 만드는 일련의 과정이기 때문에 하나의 함수로 만들면 더 깔끔했을듯

2024-04-14 11:10 UTC, MinQyu commented
sort().join()하는 과정을 함수화하고, 정렬한 spell을 상수로 선언함

2024-04-16 06:02 UTC, hyeonQyu commented
for문에서 break 쓰던거는 왜 forEach로 바꾼거지?

2024-04-16 06:48 UTC, MinQyu commented
오랜만에 다시 봐서 배열을 다 탐색할 필요가 없다는걸 잊고, 깔끔하게 만들어야지 하다가 dic.length만큼 돌거면 forEach 쓰자 생각해서 바꾼듯.  다시 for로 수정.

2024-04-27 15:14 UTC, merged