입문/로그인 성공?
MinQyu/algorithm pull request #74
Opened 2024-01-28 12:29 UTC by MinQyu

https://school.programmers.co.kr/learn/courses/30/lessons/120883

2024-04-16 06:05 UTC, hyeonQyu requested changes
이미 할당되어있는 변수에 값을 재할당하는 습관은 좋지 않음. 여기서 state와 db에 새로 값을 할당하고 있음. state는 미리 선언되어있을 필요가 없으며 db는 기존 db 변수에다 재할당 할 것이 아니라 새로운 변수를 만드는 것이 맞음

2024-04-16 07:34 UTC, MinQyu commented
필터링된 db를 새로운 변수에 할당함. 
state를 변수에 할당하지 않고, 조건에 따라 문자열을 리턴하도록 변경

2024-04-24 06:58 UTC, hyeonQyu commented on programmersJS/로그인 성공.js
> +  const parsedDB = db.filter((e) => e[0] === id).flat();
이부분도 e[0] 대신에
db.filter(([currentId]) => currentId === id).flat();
이렇게 썼으면 좋았을듯
아래 parsedDB[1]도 마찬가지

2024-04-24 22:43 UTC, hyeonQyu approved these changes

2024-04-27 15:16 UTC, merged