입문/등수 매기기
MinQyu/algorithm pull request #75
Opened 2024-01-28 12:45 UTC by MinQyu

https://school.programmers.co.kr/learn/courses/30/lessons/120882

2024-04-16 06:06 UTC, hyeonQyu requested changes

2024-04-16 06:06 UTC, hyeonQyu commented on programmersJS/등수 매기기.js
> +    score = score.map(e => (e[0] + e[1]) / 2);
score 재할당하는건 좋지 않음
이게 기존 score 배열을 왜 어떤 이유에서 변형시켰는지 이름으로 표현해주면 좋음

2024-04-16 07:44 UTC, MinQyu commented
score을 재할당하는 대신 averageScore로 선언하고, 정렬한 배열의 이름도 sortedAverageScore로 변경

2024-04-24 22:45 UTC, hyeonQyu approved these changes

2024-04-27 15:17 UTC, merged