기초/문자열 붙여서 출력하기
MinQyu/algorithm pull request #8
Opened 2023-12-26 09:34 UTC by MinQyu

https://school.programmers.co.kr/learn/courses/30/lessons/181946?language=javascript

JS 강의에서 알려준 방법으로 출력. 답은 맞았으나 이벤트 리스너 구조는 생소해서 chatGPT로 공부

2023-12-27 04:40 UTC, hyeonQyu commented
답이 맞았다고? 기본 코드랑 뭐가 다른거지?

2023-12-27 04:46 UTC, hyeonQyu requested changes
코드 확인

2023-12-28 10:31 UTC, MinQyu commented
코드 수정

2024-01-06 08:24 UTC, hyeonQyu approved these changes

2024-01-07 02:19 UTC, merged